# Generated by Django 2.1.2 on 2018-11-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20181101_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='movieId',
        ),
    ]
