# Generated by Django 2.1.2 on 2018-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20181101_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbId',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='userId',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
